#!/usr/bin/env php
<?php

declare(strict_types=1);

require __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/vendor/yiisoft/yii2/Yii.php';
require __DIR__ . '/src/config/aliases_console.php';

use yii\console\Application;
use Dotenv\Dotenv;

$rootPath = Yii::getAlias('@root');
$appPath = Yii::getAlias('@app');

(Dotenv::createUnsafeImmutable(
        $rootPath,
        ['.env'],
        false
))->load();

$config = require $appPath . '/config/console.php';

exit(
    (new Application($config))->run()
);
